name: CI

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main
      - "feature/*"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # You can adjust to the version of Node.js you're using.

      # Cache dependencies to speed up builds
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code
      - name: Run ESLint
        run: npm run lint

      # Format the code
      - name: Run Prettier
        run: npm run format

      # Run tests with Vitest
      - name: Run tests
        run: npm run test

      # Build the project (optional, depending on your workflow)
      - name: Build project
        run: npm run build

      # Optionally, you can check for coverage if you want
      - name: Run coverage
        run: npm run test:coverage

  # You can add more jobs such as deploying or running Lighthouse CI (lhci)
  # If you want to add Lighthouse CI to this action:
  lhci:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: npm run lhci
