name: CI

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main
      - "feature/*"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # You can adjust to the version of Node.js you're using.

      # Cache dependencies to speed up builds
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Cache Cypress binary directory
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Ensure Cypress binary is installed (this will only run if the binary is missing)
      - name: Install Cypress
        run: npx cypress install

      # Lint the code
      - name: Run ESLint
        run: npm run lint

      # Format the code
      - name: Run Prettier
        run: npm run format

      # Run tests with Vitest
      - name: Run tests
        run: npm run test

      # Build the project (optional, depending on your workflow)
      - name: Build project
        run: npm run build

      # Optionally, you can check for coverage if you want
      - name: Run coverage
        run: npm run test:coverage

      # Optionally, you can check for coverage if you want
      - name: Run e2e
        run: npm run e2e

  # You can add more jobs such as deploying or running Lighthouse CI (lhci)
  # If you want to add Lighthouse CI to this action:
  lhci:
    runs-on: ubuntu-latest
    needs: setup
    env: # Set environment variables globally for this job
      LHCI_URL: https://homework-rdd.vercel.app
      LHCI_RUN: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: npm run lhci
